{{- range $rbac := .Values.customrbac.rolebindings }}
  {{- range $binding := $rbac.bindings }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $.Release.Name }}-{{ $rbac.rolename }}-{{ $binding.namespace }}-binding
  namespace: {{ $binding.namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  {{- if eq (lower $rbac.rolekind) "role" }}
  kind: Role
  {{- else }}
  kind: ClusterRole
  {{- end }}
  name: {{ $rbac.rolename | quote }}
subjects:
    {{- range $user := $binding.subjects.users }}
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ $user | quote }}
    {{- end }}
    {{- range $group := $binding.subjects.groups }}
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: {{ $group | quote }}
    {{- end }}
    {{- range $account := $binding.subjects.serviceaccounts }}
- apiGroup: rbac.authorization.k8s.io
  kind: ServiceAccount
  name: {{ $account | quote }}
    {{- end }}
  {{- end }}
{{- end }}
