{{- range $role := .Values.customrbac.roles }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $role.name }}
  namespace: {{ $role.namespace }}
rules:
{{ $role.rules | toYaml }}
{{- end }}
